.travis.yml, cache.go, cache_test.go, client.go, client_test.go, fs.go, fs_test.go, keywhizfs/main.go, secret_test.go, secretmap_test.go
Enable Travis by adding yml file, runs tests on pull requests and pushes
=> add travis CI config to keywhiz-fs

Dockerfile, README.md, docker_kwfs.sh
Added Dockerfile to build keywhiz-fs.
I tried really hard to make it not run as root. As you can see, it doesn't look pretty.
@huslage @jfrazelle @alokmenghrajani @mbentley @normalfaults
=> Added Dockerfile

client.go, client_test.go, fs_test.go, keywhizfs/main.go
=> Fixes https://github.com/square/keywhiz-fs/issues/15

client.go
Fixes https://github.com/square/keywhiz-fs/issues/16
=> Improve error messages.

keywhizfs/main.go
=> Handle signals and exit cleanly.

README.md
Golang's flag library supports both forms. -- feels more natural.
=> nit: update doc to use -- instead of -

.gitignore, .travis.yml, Makefile, README.md, glide.lock, glide.yaml
=> Vendor dependencies using glide.

keywhizfs/main.go
r: @alokmenghrajani @mcpherrinm 
Support custom metrics prefix
=> Support custom metrics prefix

cache_test.go, client.go, client_test.go, fs_test.go, ownership_test.go, secretmap_test.go
@alokmenghrajani @mcpherrinm @sqshh 
Adds lots more tests, mostly to test error/edge cases.
=> Add more tests

Makefile, client.go, fs.go, fs_test.go, main.go, util_test.go
r: @mcpherrinm 
Exposes build revision in `.version` and compiler version in `.compiler`.
=> Expose revision/runtime version

cache.go, client.go, client_test.go, fs_test.go, main.go
=> Prime secrets list cache on startup

log/log.go, main.go
=> Add flag to control if logs should go to syslog

main.go
@mcpherrinm @sqshh @alokmenghrajani 
Bump deadlines up
=> Bump deadlines up

ownership.go, ownership_test.go
@mcpherrinm 
Parse /etc/group to lookup gid
=> Parse /etc/group to lookup gid

fs.go, log/log.go
@mcpherrinm @alokmenghrajani 
Fix linter errors
=> Fix linter errors

ownership.go, ownership_test.go
@mcpherrinm @alokmenghrajani 
More tests for ownership.go
=> More tests for ownership.go

mount.kwfs
Should be useful for anyone using /etc/fstab to setup their kwfs mounts.
=> Add mount.kwfs

fs.go, fs_test.go
Before, calling fstat always returned 0644.
Now, it fstat should match stat.
TODO: Tests.
=> Proper fstat implementation

fs.go, fs_test.go
This correctly sets the rest of fstat, not just the mode.
WIP: tests fail still, but it's friday night and I can fix it later :)
=> Fix fstat implementation: Previous impl only correctly returned mode

glide.lock
@alokmenghrajani @mcpherrinm @sqshh 
Bump go-fuse dependency
=> Bump go-fuse dependency

fs.go
use with: go tool pprof keywhiz-fs mount/.pprof/heap
WIP, needs some cleanup & maybe testing.  
pprof stuff:
goroutine - stack traces of all current goroutines
heap - a sampling of all heap allocations
Could maybe do something a bit more dynamic to get everything pprof supports automagically work here.
=> Add heap profile to filesystem.

Makefile
@alokmenghrajani @mcpherrinm @sqshh 
Strip runtime to reduce binary size
=> Strip runtime to reduce binary size

README.md, main.go
r @alokmenghrajani 
Add flag for enabling/disabling mlockall
=> Add flag for enabling/disabling mlockall

glide.lock, main.go
=> Update for configurable metrics interval (hardcoded to 30s)

README.md, cache.go, main.go
r: @mcpherrinm @alokmenghrajani @worldwise001 
Remove ping, add cache warmup mechanism (best-effort) instead.
=> Remove ping, add cache warmup

cache.go, cache_test.go
r: @alokmenghrajani @mcpherrinm @worldwise001
=> Simplify caching logic

cache.go, cache_test.go, secretmap.go
Paired with scottf on this change.
=> Fix caching edge case

main.go
Moved up to before file system mount
=> Moved initial Cache.Warmup() to earlier in the startup process

fs.go
@worldwise001 @stfinney @jbpeirce
=> Make stat, open, opendir async with timeout

fs.go
@mcpherrinm @worldwise001 @jbpeirce @stfinney 
Dump goroutines on FS timeout. Use 2x MaxWait as the FS timeout. We expect the client to never take longer than MaxWait time, so 2x MaxWait seems like a reasonable time to limit FS operations to.
=> Dump goroutines on FS timeout

fs.go, fs_test.go
@jbpeirce @worldwise001 @stfinney
=> Show .pprof dir, enable profile debug output

client.go
@stfinney @jbpeirce @mcpherrinm @worldwise001
=> Use atomic pointers for holding on to http client

fs.go
=> Make Access to... message a Debugf

log/log.go
@mcpherrinm @stfinney @worldwise001 @jbpeirce 
Non-blocking log wrapper, so we never block on syslog.
=> Non-blocking log wrapper

cache.go, fs.go
Avoid channel/goroutine leaks on timeouts
=> Avoid channel/goroutine leaks on timeouts
